config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :online_peer_and_recovery_resources
  resources :in_person_interest_resources
  resources :in_person_wellbeing_resources
  resources :in_person_recovery_resources
  get "home/index"
  resources :community_resources
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  get '/print_resource_sheet', to: "home#print"
  get '/tagged', to: "in_person_recovery_resources#tagged"
  get '/wellbeing_tagged', to: "in_person_wellbeing_resources#tagged"
  get '/interest_tagged', to: "in_person_interest_resources#tagged"
  get '/peer_tagged', to: "online_peer_and_recovery_resources#tagged"

  root :to => "home#index"

  # root :to => "in_person_recovery_resources#index"
end

app/models/in_person_interest_resource.rb
class InPersonInterestResource < ApplicationRecord
   acts_as_taggable_on :interests_tags
end

app/controllers/in_person_interest_resources_controller.rb
class InPersonInterestResourcesController < ApplicationController
  before_action :set_in_person_interest_resource, only: %i[ show edit update destroy ]

  # GET /in_person_interest_resources or /in_person_interest_resources.json
  def index
    @in_person_interest_resources = InPersonInterestResource.all
  end

  # GET /in_person_interest_resources/1 or /in_person_interest_resources/1.json
  def show
  end

  # GET /in_person_interest_resources/new
  def new
    @in_person_interest_resource = InPersonInterestResource.new
  end

  # GET /in_person_interest_resources/1/edit
  def edit
  end

  # POST /in_person_interest_resources or /in_person_interest_resources.json
  def create
    @in_person_interest_resource = InPersonInterestResource.new(in_person_interest_resource_params)

    respond_to do |format|
      if @in_person_interest_resource.save
        format.html { redirect_to @in_person_interest_resource, notice: "In person interest resource was successfully created." }
        format.json { render :show, status: :created, location: @in_person_interest_resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @in_person_interest_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /in_person_interest_resources/1 or /in_person_interest_resources/1.json
  def update
    respond_to do |format|
      if @in_person_interest_resource.update(in_person_interest_resource_params)
        format.html { redirect_to @in_person_interest_resource, notice: "In person interest resource was successfully updated." }
        format.json { render :show, status: :ok, location: @in_person_interest_resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @in_person_interest_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /in_person_interest_resources/1 or /in_person_interest_resources/1.json
  def destroy
    @in_person_interest_resource.destroy!

    respond_to do |format|
      format.html { redirect_to in_person_interest_resources_path, status: :see_other, notice: "In person interest resource was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def tagged
    if params[:interests_tag_list].present?
      @in_person_interest_resources = InPersonInterestResource.tagged_with(params[:interests_tag_list])
    elsif params[:services_tag_list].present?
      @in_person_interest_resources = InPersonInterestResource.tagged_with(params[:services_tag_list])
    else
      @in_person_interest_resources = InPersonInterestResource.all
    end
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_in_person_interest_resource
      @in_person_interest_resource = InPersonInterestResource.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def in_person_interest_resource_params
      params.require(:in_person_interest_resource).permit(:name, :address, :bus_routes, :phone, :website, :monday_opening_hours, :monday_closing_hours, :tuesday_opening_hours, :tuesday_closing_hours, :wednesday_opening_hours, :wednesday_closing_hours, :thursday_opening_hours, :thursday_closing_hours, :friday_opening_hours, :friday_closing_hours, :saturday_opening_hours, :saturday_closing_hours, :sunday_opening_hours, :sunday_closing_hours, :information, :pricing_accomodations, :services_tag_list, :interests_tag_list)
    end
end

app/helpers/in_person_interest_resources_helper.rb
module InPersonInterestResourcesHelper
end

app/views/in_person_interest_resources/_form.html.erb
<% if user_signed_in? %>
  <%= form_with(model: in_person_interest_resource, :html => {:class => 'resource-form'}) do |form| %>
    <% if in_person_interest_resource.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(in_person_interest_resource.errors.count, "error") %> prohibited this in_person_interest_resource from being saved:</h2>

        <ul>
          <% in_person_interest_resource.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, :required => true, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :address, style: "display: block" %>
      <%= form.text_field :address, :required => true, class: "form-control" %>
    </div>
    
    <div class="form-field">
      <%= form.label :bus_routes, style: "display: block" %>
      <%= form.text_field :bus_routes, class: "form-control" %>
    </div class="form-field">

     <div class="form-field">
      <%= form.label :phone, style: "display: block" %>
      <%= form.text_field :phone, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :website, style: "display: block" %>
      <%= form.text_field :website, :required => true, class: "form-control" %>
    </div class="form-field">


    <div class="form-field">
      <label style="display: block">Hours of Operation</label>
      <table>
        <tr>
          <th></th>
          <th>Opens at:</th>
          <th>Closes at:</th>
        </tr>
        <tr>
          <td>Monday</td>
          <td><%= form.time_field :monday_opening_hours, class: "form-control" %></td>
          <td><%= form.time_field :monday_closing_hours, class: "form-control" %></td>
        </tr>
        <tr>
          <td>Tuesday</td>
          <td><%= form.time_field :tuesday_opening_hours, class: "form-control" %></td>
          <td><%= form.time_field :tuesday_closing_hours, class: "form-control" %></td>
        </tr>
        <tr>
          <td>Wednesday</td>
          <td><%= form.time_field :wednesday_opening_hours, class: "form-control" %></td>
          <td><%= form.time_field :wednesday_closing_hours, class: "form-control" %></td>
        </tr>
        <tr>
          <td>Thursday</td>
          <td><%= form.time_field :thursday_opening_hours, class: "form-control" %></td>
          <td><%= form.time_field :thursday_closing_hours, class: "form-control" %></td>
        </tr>
        <tr>
          <td>Friday</td>
          <td><%= form.time_field :friday_opening_hours, class: "form-control" %></td>
          <td><%= form.time_field :friday_closing_hours, class: "form-control" %></td>
        </tr>
        <tr>
          <td>Saturday</td>
          <td><%= form.time_field :saturday_opening_hours, class: "form-control" %></td>
          <td><%= form.time_field :saturday_closing_hours, class: "form-control" %></td>
        </tr>
        <tr>
          <td>Sunday</td>
          <td><%= form.time_field :sunday_opening_hours, class: "form-control" %></td>
          <td><%= form.time_field :sunday_closing_hours, class: "form-control" %></td>
        </tr>
      </table>
    </div>

    <div class="form-field">
      <%= form.label :information, style: "display: block" %>
      <%= form.text_area :information, :required => true, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :pricing_accomodations, style: "display: block" %>
      <%= form.text_area :pricing_accomodations, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :interests_tag_list, "Interest Tags" %>
      <%=
        form.text_field :interests_tag_list,
        value: @in_person_interest_resource.send(:interests_tag_list).to_s,
        placeholder: 'Art, Gardening, Writing, Etc'
      %>
    </div>

    <div class="form-submit-container">
      <%= form.submit :value => "Update In Person Interest Resource", :class => 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

app/views/in_person_interest_resources/_in_person_interest_resource.html.erb
<style>
  .resource-display__add-container {
    text-align: right;
    font-size: 2em;
    color: #c73333;
    padding-top: 10px;
  }
</style>

<script type="text/javascript">

// $(function() { 
//     // Initialize communityActivities array from sessionStorage or as an empty array
//     const communityActivities = JSON.parse(sessionStorage.getItem('communityActivities')) || [];
//     const $resourceButtons = $(".resource-display__add");

//     // Function to fetch and add resource data by id
//     function addResourceData(id) {
//         $.getJSON(`/in_person_interest_resources/${id}.json`)
//             .done((data) => {
//                 communityActivities.push(data);
//                 sessionStorage.setItem('communityActivities', JSON.stringify(communityActivities));
//             })
//             .fail(() => console.error(`Failed to fetch data for resource with id: ${id}`));
//     }

//     // Function to remove resource data by id
//     function removeResourceData(id) {
//       const updatedItems = communityActivities.filter(item => item.id !== id);
//       sessionStorage.setItem('communityActivities', JSON.stringify(updatedItems));
//     }

//     // Function to update button icon based on whether resource exists
//     function updateButtonIcon($button, exists) {
//         $button.toggleClass("fa-plus-circle", exists);
//         $button.toggleClass("fa-minus-circle");
//     }

//     // Event handler for resource-display__add button clicks
//     $resourceButtons.on("click", function() {
//         const id = $(this).data("id");
//         if($(this).hasClass("fa-plus-circle")){
//           addResourceData(id);
//         }
//         else if ($(this).hasClass("fa-minus-circle")) {
//           removeResourceData(id);
//         }
        
//     });

//     // Check if resources already exist and update button icons accordingly
//     $resourceButtons.each(function () {
//         const id = $(this).data("id");
//         const exists = communityActivities.some(activity => activity.id === id);
//         updateButtonIcon($(this), exists);
//     });
// });


</script>


<div id="<%= dom_id in_person_interest_resource %>" data-id="<%= in_person_interest_resource.id %>" class="resource-display">

  <div class="resource-display__add-container">
    <div class="circle-plus closed">
      <div class="circle">
        <div class="horizontal"></div>
        <div class="vertical"></div>
      </div>
    </div>
  </div>

  <div class="display-field">
    <div class="field-label"><strong>Name:</strong></div>
    <div class="field-value"><%= in_person_interest_resource.name %></div>
  </div>

  <div class="display-field">
    <div class="field-label"><strong>Address:</strong></div>
    <div class="field-value"><%= in_person_interest_resource.address %></div>
  </div>

  <div class="display-field">
    <div class="field-label"><strong>Phone:</strong></div>
    <% if in_person_interest_resource.phone != "" %>
      <div class="field-value"><%= in_person_interest_resource.phone %></div>
    <% else %>
      <div class="field-value">Not listed.</div>
    <% end %>
  </div>

  <div class="display-field">
    <div class="field-label"><strong>Website:</strong></div>
    <% if in_person_interest_resource.website != "" %>
      <div class="field-value">
        <a href="<%= in_person_interest_resource.website %>"><%= in_person_interest_resource.website %></a>
      </div>
    <% else %>
      <div class="field-value">Not listed.</div>
    <% end %>
  </div>

  <div class="display-field">
    <div class="field-label"><strong>Bus routes:</strong></div>
    <% if in_person_interest_resource.bus_routes != "" and in_person_interest_resource.bus_routes != nil %>
      <div class="field-value">
        <%= in_person_interest_resource.bus_routes %>
      </div>
    <% else %>
      <div class="field-value">Not listed.</div>
    <% end %>
  </div>

  <div class="display-field display-field__big-field">
    <div class="field-label"><strong>Hours of Operation:</strong></div>
    <div class="field-value">
      <table>
        <tr>
          <th></th>
          <th>Opens at:</th>
          <th>Closes at:</th>
        </tr>

        <% ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"].each do |day| %>
          <tr>
            <td><strong><%= day.capitalize %></strong></td>
            <% if in_person_interest_resource["#{day}_opening_hours"].present? && in_person_interest_resource["#{day}_closing_hours"].present? %>
              <td><%= in_person_interest_resource["#{day}_opening_hours"].strftime('%I:%M %p') %></td>
              <td><%= in_person_interest_resource["#{day}_closing_hours"].strftime('%I:%M %p') %></td>
            <% else %>
              <td>Closed</td>
              <td>Closed</td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <% if in_person_interest_resource.pricing_accomodations != "" and in_person_interest_resource.pricing_accomodations != nil %>
  <div class="display-field display-field__big-field">
    <div class="field-label"><strong>Pricing Accomodations:</strong></div>
    <div class="field-value"><%= in_person_interest_resource.pricing_accomodations %></div>
  </div>
  <% end %>

  <div class="display-field display-field__big-field">
    <div class="field-label"><strong>Information:</strong></div>
    <div class="field-value"><%= in_person_interest_resource.information %></div>
  </div>

  <% if in_person_interest_resource.interests_tag_list.length != 0 %>
  <div class="display-field">
    <div class="field-label"><strong>Interests Tags:</strong></div>
    <div class="field-value">
      <% in_person_interest_resource.interests_tag_list.each do |t| %>
          <%= link_to t, interest_tagged_path(tag: t) %><br/>
      <% end %>
    </div>
  </div>
  <% end %>


</div>

app/views/in_person_interest_resources/edit.html.erb
<% content_for :title, "Editing in person interest resource" %>

<h1>Editing in person interest resource</h1>

<%= render "form", in_person_interest_resource: @in_person_interest_resource %>

<br>

<div>
  <%= link_to "Show this in person interest resource", @in_person_interest_resource %> |
  <%= link_to "Back to in person interest resources", in_person_interest_resources_path %>
</div>

app/views/in_person_interest_resources/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "In person interest resources" %>

<h1>In person interest resources</h1>

<div id="in_person_interest_resources">
  <% @in_person_interest_resources.each do |in_person_interest_resource| %>
    <%= render in_person_interest_resource %>
    <p>
      <%= link_to "Show this in person interest resource", in_person_interest_resource %>
    </p>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= link_to "New in person interest resource", new_in_person_interest_resource_path %>
<% end %>

app/views/in_person_interest_resources/new.html.erb
<% content_for :title, "New in person interest resource" %>

<h1>New in person interest resource</h1>

<%= render "form", in_person_interest_resource: @in_person_interest_resource %>

<br>

<div>
  <%= link_to "Back to in person interest resources", in_person_interest_resources_path %>
</div>

app/views/in_person_interest_resources/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @in_person_interest_resource %>

<div>
  <% if user_signed_in? %>
    <%= link_to "Edit this in person interest resource", edit_in_person_interest_resource_path(@in_person_interest_resource) %> |
  <% end %>

  <%= link_to "Back to in person interest resources", in_person_interest_resources_path %>

  <% if user_signed_in? %>
    <%= button_to "Destroy this in person interest resource", @in_person_interest_resource, method: :delete %>
  <% end %>
</div>

app/views/in_person_interest_resources/tagged.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "In person interest resources" %>

<h1 class="page-heading">In person interest resources</h1>
<h3 class="tagged-with">Tagged with "<strong><i><%= params[:tag] %></i></strong>"</h3>

<div id="in_person_interest_resources">
  <% @in_person_interest_resources.tagged_with(params[:tag]).each do |in_person_interest_resource| %>
    <%= render in_person_interest_resource %>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= link_to "New in person interest resource", new_in_person_interest_resource_path %>
<% end %>