config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :online_peer_and_recovery_resources
  resources :in_person_interest_resources
  resources :in_person_wellbeing_resources
  resources :in_person_recovery_resources
  get "home/index"
  resources :community_resources
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  get '/print_resource_sheet', to: "home#print"
  get '/tagged', to: "in_person_recovery_resources#tagged"
  get '/wellbeing_tagged', to: "in_person_wellbeing_resources#tagged"
  get '/interest_tagged', to: "in_person_interest_resources#tagged"
  get '/peer_tagged', to: "online_peer_and_recovery_resources#tagged"

  root :to => "home#index"

  # root :to => "in_person_recovery_resources#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def print
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<div class="page-heading-container">
	<h1 class="page-heading__bold">DIY Mini Case Management Tool</h1>
	<p>This is an atlas of free and sliding scale resources that are meant to support the mental, physical, and emotional wellbeing of folks located on Cowlitz, Multnomah, and Clackamas land (referred to as Multnomah County, Oregon).</p>
</div>


<div class="home__resource-container">
	<div class="resource-link">
	  <h2><%= link_to "Interest-Based Activities", in_person_interest_resources_path %></h2>
	</div>
	<div class="resource-description">
	  Located in Multnomah County, all options are <u><strong>in person</strong></u> and <u><strong>free and reduced cost</strong></u>. Options include things like art, print making, gardening, and many other interests.
	</div>
</div>

<div class="home__resource-container">
	<div class="resource-link">
	  <h2><%= link_to "In Person Recovery Resources", in_person_recovery_resources_path %></h2>
	</div>
	<div class="resource-description">
	 A list of a variety of in person recovery resources in Multnomah County. Includes a wide variety of:<br />
  	<ul>
	  <li>
	  	<strong>Recovery models:</strong> Including (but not limited to) Recovery Dharma, Wellbreity (Native-based recovery pathway), AA, SMART, NA, Al-Anon, and many more.
	  </li>
	  <li>
	  	<strong>Culturally-specific resources</strong>: Locations and groups specifically for queer/LGBTQIA+, BIPOC, Native, Latiné/a/o/x, Women's, and Men's, etc.
	  </li>
	  <li>
	  	<strong>More than just meetings:</strong> Recovery gyms, art, free cooking classes, events, and many more options to engage in supportive community.
	  </li>
	</ul>
	</div>
</div>

<div class="home__resource-container">
	<div class="resource-link">
	  <h2><%= link_to "Online Peer & Recovery Groups", online_peer_and_recovery_resources_path %></h2>
	</div>
	<div class="resource-description">
	  A comprehensive listing of peer support groups as well as recovery-based groups. <strong>Peer support groups</strong> are nonclinical groups meant to talk with other folk openly who share a similar lived experience (such as Autism, suicidality, shared-identity-based experiences, etc). <strong>Recovery groups</strong> are meant for folks to get support who live with addiction. A group can be one or both.
	</div>
</div>

<div class="home__resource-container">
	<div class="resource-link">
	  <h2><%= link_to "Community Wellbeing Resources", in_person_wellbeing_resources_path %></h2>
	</div>
	<div class="resource-description">
	  Community well being resources are offerings in the community such as job/resume help, rental assistance, food pantries, reduced/free cellphone access, disability help, bus passes, etc. We <i>highly</i> recommend you also visit <a href="https://www.211info.org/">211info.org</a> and <a href="https://www.findhelp.org/">findhelp.org</a>.
	</div>
</div>

app/views/home/print.html.erb
<div class="page-heading-container" style="height:70vh;">
	<h1 class="page-heading__bold">Still need to code this out</h1>
	<p>This will list a printer-friendly version of all the resources "added(+)" so folk can print off a sheet of self-selected resources.</p>
</div>