config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :online_peer_and_recovery_resources
  resources :in_person_interest_resources
  resources :in_person_wellbeing_resources
  resources :in_person_recovery_resources
  get "home/index"
  resources :community_resources
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  get '/print_resource_sheet', to: "home#print"
  get '/tagged', to: "in_person_recovery_resources#tagged"
  get '/wellbeing_tagged', to: "in_person_wellbeing_resources#tagged"
  get '/interest_tagged', to: "in_person_interest_resources#tagged"
  get '/peer_tagged', to: "online_peer_and_recovery_resources#tagged"

  root :to => "home#index"

  # root :to => "in_person_recovery_resources#index"
end

app/models/online_peer_and_recovery_resource.rb
class OnlinePeerAndRecoveryResource < ApplicationRecord
  acts_as_taggable_on :lived_experience_tags
end

app/controllers/online_peer_and_recovery_resources_controller.rb
class OnlinePeerAndRecoveryResourcesController < ApplicationController
  before_action :set_online_peer_and_recovery_resource, only: %i[ show edit update destroy ]

  # GET /online_peer_and_recovery_resources or /online_peer_and_recovery_resources.json
  def index
    @online_peer_and_recovery_resources = OnlinePeerAndRecoveryResource.all
  end

  # GET /online_peer_and_recovery_resources/1 or /online_peer_and_recovery_resources/1.json
  def show
  end

  # GET /online_peer_and_recovery_resources/new
  def new
    @online_peer_and_recovery_resource = OnlinePeerAndRecoveryResource.new
  end

  # GET /online_peer_and_recovery_resources/1/edit
  def edit
  end

  # POST /online_peer_and_recovery_resources or /online_peer_and_recovery_resources.json
  def create
    @online_peer_and_recovery_resource = OnlinePeerAndRecoveryResource.new(online_peer_and_recovery_resource_params)

    respond_to do |format|
      if @online_peer_and_recovery_resource.save
        format.html { redirect_to @online_peer_and_recovery_resource, notice: "Online peer and recovery resource was successfully created." }
        format.json { render :show, status: :created, location: @online_peer_and_recovery_resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @online_peer_and_recovery_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /online_peer_and_recovery_resources/1 or /online_peer_and_recovery_resources/1.json
  def update
    respond_to do |format|
      if @online_peer_and_recovery_resource.update(online_peer_and_recovery_resource_params)
        format.html { redirect_to @online_peer_and_recovery_resource, notice: "Online peer and recovery resource was successfully updated." }
        format.json { render :show, status: :ok, location: @online_peer_and_recovery_resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @online_peer_and_recovery_resource.errors, status: :unprocessable_entity }
      end
    end
  end


  def tagged
    if params[:lived_experience_tag_list].present?
      @online_peer_and_recovery_resources = OnlinePeerAndRecoveryResource.tagged_with(params[:lived_experience_tag_list])
    else
      @online_peer_and_recovery_resources = OnlinePeerAndRecoveryResource.all
    end
  end

  # DELETE /online_peer_and_recovery_resources/1 or /online_peer_and_recovery_resources/1.json
  def destroy
    @online_peer_and_recovery_resource.destroy!

    respond_to do |format|
      format.html { redirect_to online_peer_and_recovery_resources_path, status: :see_other, notice: "Online peer and recovery resource was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_online_peer_and_recovery_resource
      @online_peer_and_recovery_resource = OnlinePeerAndRecoveryResource.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def online_peer_and_recovery_resource_params
      params.require(:online_peer_and_recovery_resource).permit(:name, :hosting_org, :hosting_org_website, :time_of_meetings, :how_to_access, :description, :lived_experience_tag_list)
    end
end

app/helpers/online_peer_and_recovery_resources_helper.rb
module OnlinePeerAndRecoveryResourcesHelper
end

app/views/online_peer_and_recovery_resources/_form.html.erb
<% if user_signed_in? %>
  <%= form_with(model: online_peer_and_recovery_resource, :html => {:class => 'resource-form'}) do |form| %>
    <% if online_peer_and_recovery_resource.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(online_peer_and_recovery_resource.errors.count, "error") %> prohibited this online_peer_and_recovery_resource from being saved:</h2>

        <ul>
          <% online_peer_and_recovery_resource.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, :required => true, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :hosting_org, style: "display: block" %>
      <%= form.text_field :hosting_org, :required => true, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :hosting_org_website, style: "display: block" %>
      <%= form.text_field :hosting_org_website, :required => true, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :time_of_meetings, style: "display: block" %>
      <%= form.text_field :time_of_meetings, :required => true, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :how_to_access, style: "display: block" %>
      <%= form.text_area :how_to_access, :required => true, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description, :required => true, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :lived_experience_tag_list, "Lived Experiences" %>
      <%=
        form.text_field :lived_experience_tag_list,
        value: @online_peer_and_recovery_resource.send(:lived_experience_tag_list).to_s,
        placeholder: 'Autism, Hearing Voices, Etc'
      %>
    </div>

    <div class="form-submit-container">
      <%= form.submit :value => "Update Online Peer and Recovery Resource", :class => 'btn btn-primary'  %>
    </div>
  <% end %>
<% end %>

app/views/online_peer_and_recovery_resources/_online_peer_and_recovery_resource.html.erb
<div id="<%= dom_id online_peer_and_recovery_resource %>" class="resource-display">
  <div class="resource-display__add-container">
    <div class="circle-plus closed">
      <div class="circle">
        <div class="horizontal"></div>
        <div class="vertical"></div>
      </div>
    </div>
  </div>
  <div class="display-field">
    <div class="field-label"><strong>Name:</strong></div>
    <div class="field-value"><%= online_peer_and_recovery_resource.name %></div>
  </div>

  <div class="display-field">
    <div class="field-label"><strong>Hosting org:</strong></div>
    <div class="field-value"><%= online_peer_and_recovery_resource.hosting_org %></div>
  </div>

  <div class="display-field">
    <div class="field-label"><strong>Hosting org website:</strong></div>
    <div class="field-value">
      <a href="<%= online_peer_and_recovery_resource.hosting_org_website %>">
        <%= online_peer_and_recovery_resource.hosting_org_website %>
      </a>
    </div>
  </div>

  <div class="display-field">
    <div class="field-label"><strong>Time of meetings:</strong></div>
    <div class="field-value"><%= online_peer_and_recovery_resource.time_of_meetings %></div>
  </div>

  <div class="display-field">
    <div class="field-label"><strong>How to access:</strong></div>
    <div class="field-value"><%= online_peer_and_recovery_resource.how_to_access %></div>
  </div>

  <div class="display-field">
    <div class="field-label"><strong>Description:</strong></div>
    <div class="field-value"><%= online_peer_and_recovery_resource.description %></div>
  </div>

  <% if online_peer_and_recovery_resource.lived_experience_tag_list.length != 0 %>
  <div class="display-field">
    <div class="field-label"><strong>Lived Experience Tags:</strong></div>
    <div class="field-value">
      <% online_peer_and_recovery_resource.lived_experience_tag_list.each do |t| %>
        <%= link_to t, peer_tagged_path(tag: t) %><br/>
      <% end %>
    </div>
  </div>
  <% end %>

  <div class="show-link">
    <%= link_to "Show this online peer and recovery resource", online_peer_and_recovery_resource %>
  </div>

</div>

app/views/online_peer_and_recovery_resources/edit.html.erb
<% content_for :title, "Editing online peer and recovery resource" %>

<h1>Editing online peer and recovery resource</h1>

<%= render "form", online_peer_and_recovery_resource: @online_peer_and_recovery_resource %>

<br>

<div>
  <%= link_to "Show this online peer and recovery resource", @online_peer_and_recovery_resource %> |
  <%= link_to "Back to online peer and recovery resources", online_peer_and_recovery_resources_path %>
</div>

app/views/online_peer_and_recovery_resources/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Online peer and recovery resources" %>

<h1 style="margin: 40px 0px 10px 0px;">Free, Online Peer and Recovery Resources</h1>
<p>A Google calendar view of many of these groups can also be found at <a href="https://thebigpeercalendar.org/" target="_blanket">thebigpeercalendar.org</a></p>

<div id="online_peer_and_recovery_resources">
  <% @online_peer_and_recovery_resources.each do |online_peer_and_recovery_resource| %>
    <%= render online_peer_and_recovery_resource %>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= link_to "New online peer and recovery resource", new_online_peer_and_recovery_resource_path %>
<% end %>

app/views/online_peer_and_recovery_resources/new.html.erb
<% content_for :title, "New online peer and recovery resource" %>

<h1>New online peer and recovery resource</h1>

<%= render "form", online_peer_and_recovery_resource: @online_peer_and_recovery_resource %>

<br>

<div>
  <%= link_to "Back to online peer and recovery resources", online_peer_and_recovery_resources_path %>
</div>

app/views/online_peer_and_recovery_resources/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @online_peer_and_recovery_resource %>

<div>
  <% if user_signed_in? %>
    <%= link_to "Edit this online peer and recovery resource", edit_online_peer_and_recovery_resource_path(@online_peer_and_recovery_resource) %> |
  <% end %>
  <%= link_to "Back to online peer and recovery resources", online_peer_and_recovery_resources_path %>

  <% if user_signed_in? %>
    <%= button_to "Destroy this online peer and recovery resource", @online_peer_and_recovery_resource, method: :delete %>
  <% end %>
</div>

app/views/online_peer_and_recovery_resources/tagged.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Online peer and recovery resources" %>

<h1 class="page-heading">Online peer and recovery resources</h1>
<h3>Tagged with "<%= params[:tag] %>"</h3>

<div id="online_peer_and_recovery_resources">
  <% @online_peer_and_recovery_resources.tagged_with(params[:tag]).each do |online_peer_and_recovery_resource| %>
    <%= render online_peer_and_recovery_resource %>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= link_to "New online peer and recovery resources", new_online_peer_and_recovery_resource_path %>
<% end %>